source "https://rubygems.org"
gem 'jekyll-theme-console', '> 0'
gem "github-pages", "~> 3.9.2", group: :jekyll_plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end
# Windows Specific:
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?
